<style lang="sass">
  @import "../../config.sass"
  .test-searchview
    margin: 50px auto
</style>

<template lang="pug">
  .test-searchview
    component(is="searchview", :cfg="searchview" v-if="searchview")
</template>

<script>
import searchview from 'fancy/searchview'
export default {
  components: {
    searchview,
  },
  data() {
    return {
      searchview: {
        data: [
          { id: '30', fid: '0', name: '宁夏' },
          { id: '31', fid: '0', name: '新疆' },
          { id: '32', fid: '0', name: '香港' },
          { id: '33', fid: '0', name: '澳门' },
          { id: '34', fid: '0', name: '台湾' },
          { id: '35', fid: '1', name: '北京' },
          { id: '36', fid: '35', name: '海淀' },
          { id: '37', fid: '35', name: '朝阳' },
          { id: '38', fid: '35', name: '东城' },
          { id: '39', fid: '35', name: '西城' },
          { id: '40', fid: '35', name: '崇文' },
          { id: '41', fid: '35', name: '宣武' },
          { id: '42', fid: '35', name: '丰台' },
          { id: '43', fid: '35', name: '石景山' },
          { id: '44', fid: '35', name: '房山' },
          { id: '45', fid: '35', name: '门头沟' },
          { id: '46', fid: '35', name: '通州' },
          { id: '47', fid: '35', name: '顺义' },
          { id: '48', fid: '35', name: '昌平' },
          { id: '49', fid: '35', name: '密云' },
          { id: '50', fid: '35', name: '怀柔' },
          { id: '51', fid: '35', name: '延庆' },
          { id: '52', fid: '35', name: '平谷' },
          { id: '53', fid: '35', name: '大兴' },
          { id: '54', fid: '35', name: '北京周边' },
          { id: '55', fid: '2', name: '天津' },
          { id: '56', fid: '3', name: '石家庄' },
          { id: '57', fid: '3', name: '保定' },
          { id: '58', fid: '3', name: '沧州' },
          { id: '59', fid: '3', name: '廊坊' },
          { id: '60', fid: '3', name: '秦皇岛' },
          { id: '61', fid: '3', name: '承德' },
          { id: '62', fid: '3', name: '邯郸' },
          { id: '63', fid: '3', name: '衡水' },
          { id: '64', fid: '3', name: '唐山' },
          { id: '65', fid: '3', name: '邢台' },
          { id: '66', fid: '3', name: '张家口' },
          { id: '67', fid: '4', name: '太原' },
          { id: '68', fid: '4', name: '长治' },
          { id: '69', fid: '4', name: '大同' },
          { id: '70', fid: '4', name: '晋城' },
          { id: '71', fid: '4', name: '晋中' },
          { id: '72', fid: '4', name: '临汾' },
          { id: '73', fid: '4', name: '吕梁' },
          { id: '74', fid: '4', name: '朔州' },
          { id: '75', fid: '4', name: '忻州' },
          { id: '76', fid: '4', name: '运城' },
          { id: '77', fid: '4', name: '阳泉' },
          { id: '78', fid: '5', name: '呼和浩特' },
          { id: '79', fid: '5', name: '包头' },
          { id: '80', fid: '5', name: '阿拉善盟' },
          { id: '81', fid: '5', name: '巴彦淖尔' },
          { id: '82', fid: '5', name: '赤峰' },
          { id: '83', fid: '5', name: '鄂尔多斯' },
          { id: '84', fid: '5', name: '呼伦贝尔' },
          { id: '85', fid: '5', name: '通辽' },
          { id: '86', fid: '5', name: '乌兰察布' },
          { id: '87', fid: '5', name: '乌海' },
          { id: '88', fid: '5', name: '兴安盟' },
          { id: '89', fid: '5', name: '锡林郭勒盟' },
          { id: '90', fid: '6', name: '大连' },
          { id: '91', fid: '90', name: '西岗' },
          { id: '92', fid: '90', name: '中山' },
          { id: '93', fid: '90', name: '沙河口' },
          { id: '94', fid: '90', name: '甘井子' },
          { id: '95', fid: '90', name: '旅顺口' },
          { id: '96', fid: '90', name: '金州' },
          { id: '97', fid: '90', name: '开发区' },
          { id: '98', fid: '90', name: '长兴岛' },
          { id: '99', fid: '90', name: '普兰店' },
          { id: '100', fid: '90', name: '瓦房店' },
          { id: '101', fid: '90', name: '庄河' },
          { id: '102', fid: '90', name: '其他' },
          { id: '103', fid: '6', name: '沈阳' },
          { id: '104', fid: '6', name: '鞍山' },
          { id: '105', fid: '6', name: '本溪' },
          { id: '106', fid: '6', name: '朝阳' },
          { id: '107', fid: '6', name: '丹东' },
          { id: '108', fid: '6', name: '抚顺' },
          { id: '109', fid: '6', name: '阜新' },
          { id: '110', fid: '6', name: '葫芦岛' },
          { id: '111', fid: '6', name: '锦州' },
          { id: '112', fid: '6', name: '辽阳' },
          { id: '113', fid: '6', name: '盘锦' },
          { id: '114', fid: '6', name: '铁岭' },
          { id: '115', fid: '6', name: '营口' },
          { id: '116', fid: '7', name: '长春' },
          { id: '117', fid: '116', name: '朝阳' },
          { id: '118', fid: '116', name: '宽城' },
          { id: '119', fid: '116', name: '二道' },
          { id: '120', fid: '116', name: '南关' },
          { id: '121', fid: '116', name: '绿园' },
          { id: '122', fid: '116', name: '双阳' },
          { id: '123', fid: '116', name: '榆树市' },
          { id: '124', fid: '116', name: '九台市' },
          { id: '125', fid: '116', name: '德惠市' },
          { id: '126', fid: '116', name: '农安市' },
          { id: '127', fid: '116', name: '高新技术开发区' },
        ],
      },
    }
  },
  mounted() {},
}
</script>
